name: svg_pic_editor
description: A Flutter package for SVG editing and manipulation across multiple platforms.
version: 3.2.0
homepage: https://github.com/vs-nascimento/svg_pic_editor

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  http: ^1.2.2
  shimmer: ^3.0.0
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
